# Generated by Django 5.0 on 2023-12-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("female", models.CharField(max_length=100, verbose_name="Female")),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "registration",
                    models.DateTimeField(verbose_name="Start registration"),
                ),
            ],
        ),
    ]
